---
- name: restore context
  shell: restorecon -R /
  become: yes

- name: reboot target
  shell: shutdown -r +1
  become: yes

- name: wait for port being down
  wait_for:
    host: "{{ ansible_host | default(ansible_ssh_host) | default(inventory_hostname) }}"
    port: "{{ ansible_port | default(ansible_ssh_port) | default(22) }}"
    state: stopped
  delegate_to: 127.0.0.1

- name: wait for port being up
  wait_for:
    host: "{{ ansible_host | default(ansible_ssh_host) | default(inventory_hostname) }}"
    port: "{{ ansible_port | default(ansible_ssh_port) | default(22) }}"
    state: started
  delegate_to: 127.0.0.1
